linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - errcheck
    - ineffassign

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec